### ISSUE TITLE
Add support to specify Urls in header modification 

### ISSUE THREAD

**Issue by revintec** [blunderboy/requestly#46]
I've noticed that
Modify Headers in HTTP Request and Response feature
has a limitation, it cannot match against url.

That is to say that if I choose to change a header,
requestly will make the change to all pages I visit.
What I want is only to change that header to a specific domain.
(I've looked around, didn't find a way so I assume the feature is missing)
A better way to do this is match against a url(optional setting)
before doing any work, more flexible.

I was trying to implement this and send you a pull request...
(but since I've got "lazy cancer",
and after I cloned the code,
only to found it's larger than I thought...)
Any way, it should be very easy to implement
(less than 10 lines of code if put in the right place I guess :P )
according to webRequest.onBeforeSendHeaders
(I think this is the API you use, right?)
https://developer.chrome.com/extensions/webRequest#event-onBeforeSendHeaders
there is a url parameter that you can match against.

=== further ===
Why I want this feature is that some website is poorly designed,
so I need to disable SDCH on them to prevent err::PARSING_ERROR.
And Chrome doesn't provide a way to do so,
so I've decided to change Accept-Encoding and remove sdch from it.
But I don't want to mess with other fine behaving websites.

Visite Google search,
and in DevTools you'll see that Accept-Encoding contains "sdch".
SDCH works fine with Google, but not some other site.

I currently using Header Hacker
https://chrome.google.com/webstore/detail/header-hacker/phnffahgegfkcobeaapbenpmdnkifigc
but I found requestly more powerful.
So I've tried to replace Header Hacker with requestly,
but with this feature missing, can't do.

And if you're so kindly, can you e-mail me when this feature is implemented?
caoyunbin001[at]126.com , thanks in advance.

**Comment by blunderboy** [comment]
@revintec Thank you so much for being nice to try sending a Pull Request. You know, this feature is already in my mind. Its just that I have lots of things on my plate. Nonetheless, I will try to finish this feature asap. This will be my next priority. I will target next weekend for this.

You can be sure that I will shooting an email once I implement the feature. Thanks dude!!

**Comment by revintec** [comment]
Wow, you reply very fast...
And I've been developing my own extension now :)
Got a question, can you help?

chrome.webRequest.onBeforeRequest.addListener(function(dt){
    if(!pendingRequests[dt.requestId]){
        pendingRequests[dt.requestId]=new RequestRecord(dt.requestId);
        addRecord(dt.tabId,"navigate",dt.url);
    }
},constWebReqFiltering);

Didn't always get the "navigate" record, don't know why.
If you're interested, contact me and discuss.
Best Regards

**Comment by blunderboy** [comment]
@revintec Well if you developing the Chrome Extension for Header Modification for certain Urls, I would like to stop you right here because I am almost done with this feature. You will be getting this pretty soon ;). I guess couple of days.

I tried to understand your code but it looks very abstract. Just point to me to your github repo and I will be happy to help. Moreover, StackOverflow is the best place to go for to sort out your problems at very efficient level.

**Comment by revintec** [comment]
Well, I do use stackoverflow, afterall, if you google, 80% chance it directs you to stackoverflow...
Anyway, thanks for pointing that out.
And I've done programming basically all the features I need for now.
To be specific, it's not Header-Modification that I want,
I just wanna disable SDCH, and modify the header seems the only doable way.

I didn't push my code to GitHub.
And my fault, I'll describe the question more clear:
I'm listening chrome.webRequest.onBeforeRequest,
according to doc, I shall always get this event(if my extension is running),
but the truth is that sometimes Chrome didn't trigger my callback function.
I'm just wondering if you've come into the same problem before,
if not, then it's not Chrome's fault, and I'll try to rewrite using other approaches.
I'm been checking dt.requestId against pendingRequest
because onBeforeRequest can be triggered multiple times
for THE SAME REQUEST if it involves 3xx redirects.

**Comment by blunderboy** [comment]
@revintec Since you tried to write code for the feature. I understand it was pretty bug thing to do.
Have a look at this code: https://github.com/blunderboy/requestly/commit/e862577b17e614592c844fdd59b037bb04e21c6e

I have committed this and pushed the code to Google Chrome Store So you will be getting the update in couple of hours and there you go buddy with the feature you requested!!

Please let me know in case you encounter any bugs. I will be happy to help!!

Thanks, I am closing this issue.

**Comment by blunderboy** [comment]
And about your question, I have never encountered the problem. I always get into the callback I have passed.

**Comment by revintec** [comment]
OK, I'll test more to see how exactly to reproduce the BUG.
And thanks for your great work, indeed, so much code change.
I've write the feature but since I use it for my own,
I didn't write any settings panel, so it looks easier to me.

**Comment by blunderboy** [comment]
@revintec Since I am the only developer on the Project I never know if my current code change has broken something else or not. Moreover, I do trust my code So I don't do any rigorous testing. I would really appreciate if you could just let me know if it solves your problem.

And, If you do like the feature please rate it on Chrome Store with whatever feedback you have.

Glad to hear that your code also worked. Good Job!!

**Comment by revintec** [comment]
Well, no... my code seems still having problems.
Github: https://github.com/revintec/ChromeHelper
(sorry, no time for README.md, busy fixing BUGs and implementing new features)

I don't know if it will run correctly on your computer, if not, let me know.
After you've installed it, it should be able to get "navigate" events(the blue ones)
for all newly opened tabs, but sometimes missing.
Especially when Chrome exits and then reload with all tabs,
may be a Chrome BUG since I've checked my code like 10 times...
(and yes, no error report on the console of background page)

Can you help me track it down?
And I'm writing a README.md to explain why I've created it, why it's useful.

**Comment by revintec** [comment]
@blunderboy README.md added, but I'm kind new to markdown, so no screenshot/pics in RM.md.

**Comment by revintec** [comment]
@blunderboy ...found the BUG, never thought about this...It's a major logic bug in code that will corrupt the entire database...and I hate javascript...it will be pointed early by IDE or javac if it's java...

**Comment by blunderboy** [comment]
@revintec Cool you found your mistake..I tried to look at your code but it was difficult to figure out for me.
I would be interested in knowing that. What is it ?

**Comment by revintec** [comment]
@blunderboy ...I made the mistake again, thought it would fix it but not fixed. The BUG was I try to remove the records during tab close to reclaim storage space, but operated on the wrong object(a passive example why you shouldn't code during mid-night :P ), but it didn't fix the bug... still not getting some "navigate" records
